title: Not My Blog
author: Post-Scarcity
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  There is nothing awesome about this

# social links
twitter_username: your-twitter-handle
github_username:  Post-Scarcity

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
